language: node_js
node_js:
  - "8"
  - "10"
cache: yarn
install:
  - yarn add --dev codecov
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - codecov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
