image: node:6.11.1

pipelines:
  default:
    - step:
        caches:
          - node
          - yarn
        script:
          - yarn install
          - yarn run jscs
          - yarn run build:css
          - yarn test
          - yarn run build:app
          - apt-get update
          - apt-get install python3-dev python3-pip -y --force-yes
          - pip3 install awscli --upgrade --user
          - bash scripts/upload-artifacts.sh
          - bash scripts/build-scaffold.sh
  custom:
    deploy-to-staging:
      - step:
          script:
            - echo "Running deploy to staging scripts"
    deploy-storybook:
      - step:
          script:
            - echo "Installing dependencies"
            - apt-get update && apt-get install -y rsync
            - echo "Starting build"
            - cd $BITBUCKET_CLONE_DIR
            - yarn install
            - yarn run build-storybook
            - bash scripts/storybook-deploy.sh
definitions:
  caches:
    yarn: /usr/local/share/.cache/yarn/v1
